export const cloudConfigs = {
  "aws-prod": {
    id: "aws-prod",
    name: "AWS Production",
    provider: "aws",
    criticalCount: 3,
    highCount: 7,
    lowCount: 12,
    resources: 124,
    SecurePercentage: 82,
    isPending: false,
    createdAt: new Date("2023-10-01T12:00:00Z"),
    updatedAt: new Date("2023-10-10T12:00:00Z"),
    issues: [
      {
        id: "aws-issue-1",
        rule_id: "AVD-AWS-0001",
        long_id: "aws-s3-enable-bucket-encryption",
        rule_description: "S3 Bucket has encryption disabled",
        rule_provider: "aws",
        rule_service: "s3",
        impact: "The bucket objects could be read if compromised",
        resolution:
          "Enable encryption using customer managed keys or AWS managed keys",
        links: [
          "https://docs.aws.amazon.com/AmazonS3/latest/userguide/bucket-encryption.html",
          "https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket#server_side_encryption_configuration",
        ],
        description:
          "The S3 bucket 'company-data' is configured with public read access, exposing sensitive data.",
        severity: "critical",
        resource: "s3://company-data",
        createdAt: new Date("2023-10-01T12:00:00Z"),
        updatedAt: new Date("2023-10-02T12:00:00Z"),
        location: {
          filename: "/terraform/s3.tf",
          start_line: 23,
          end_line: 25,
        },
        status: null,
        configurationId: "aws-prod",
        warning: null,
      },
      {
        id: "aws-issue-2",
        rule_id: "AVD-AWS-0057",
        long_id: "aws-iam-no-user-attached-policies",
        rule_description: "IAM user has attached policies",
        rule_provider: "aws",
        rule_service: "iam",
        impact:
          "Attaching policies to users increases the chance of privilege escalation",
        resolution:
          "Attach policies at the group level instead of the user level",
        links: [
          "https://docs.aws.amazon.com/IAM/latest/UserGuide/best-practices.html#use-groups-for-permissions",
          "https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/iam_user",
        ],
        description:
          "User 'developer1' has been granted administrator privileges which violates least privilege principle.",
        severity: "critical",
        resource: "iam::user/developer1",
        createdAt: new Date("2023-10-03T12:00:00Z"),
        updatedAt: new Date("2023-10-04T12:00:00Z"),
        location: {
          filename: "/terraform/iam.tf",
          start_line: 45,
          end_line: 52,
        },
        status: null,
        configurationId: "aws-prod",
        warning: null,
      },
      {
        id: "aws-issue-3",
        rule_id: "AVD-AWS-0089",
        long_id: "aws-rds-encrypt-instance-storage-data",
        rule_description:
          "RDS encryption has not been enabled at a DB Instance level",
        rule_provider: "aws",
        rule_service: "rds",
        impact: "Data can be read from the RDS instance if compromised",
        resolution: "Enable encryption for RDS instances",
        links: [
          "https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Overview.Encryption.html",
          "https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/db_instance#storage_encrypted",
        ],
        description:
          "RDS instance 'production-db' is not configured with encryption at rest.",
        severity: "high",
        resource: "rds:production-db",
        createdAt: new Date("2023-10-05T12:00:00Z"),
        updatedAt: new Date("2023-10-06T12:00:00Z"),
        location: {
          filename: "/terraform/rds.tf",
          start_line: 10,
          end_line: 15,
        },
        status: null,
        configurationId: "aws-prod",
        warning: null,
      },
      {
        id: "aws-issue-4",
        rule_id: "AVD-AWS-0097",
        long_id: "aws-sqs-no-wildcards-in-policy-documents",
        rule_description:
          "AWS SQS policy document has wildcard action statement.",
        rule_provider: "aws",
        rule_service: "sqs",
        impact:
          "SQS policies with wildcard actions allow more that is required",
        resolution:
          "Keep policy scope to the minimum that is required to be effective",
        links: [
          "https://aquasecurity.github.io/tfsec/v1.28.13/checks/aws/sqs/no-wildcards-in-policy-documents/",
          "https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sqs_queue_policy",
        ],
        description: "Queue policy does not restrict actions to a known set.",
        severity: "high",
        resource: "aws_sqs_queue.tfer--noter",
        createdAt: new Date("2023-10-07T12:00:00Z"),
        updatedAt: new Date("2023-10-08T12:00:00Z"),
        location: {
          filename:
            "/home/lalit/Projects/terraTest3/generated/aws/sqs/sqs_queue.tf",
          start_line: 15,
          end_line: 15,
        },
        status: null,
        configurationId: "aws-prod",
        warning: null,
      },
    ],
  },
  "azure-dev": {
    id: "azure-dev",
    name: "Azure Development",
    provider: "azure",
    criticalCount: 1,
    highCount: 4,
    lowCount: 8,
    resources: 78,
    SecurePercentage: 89,
    isPending: false,
    createdAt: new Date("2023-10-01T12:00:00Z"),
    updatedAt: new Date("2023-10-10T12:00:00Z"),
    issues: [
      {
        id: "azure-issue-1",
        rule_id: "AVD-AZR-0012",
        long_id: "azure-network-no-public-ingress",
        rule_description: "Network security rule allows public ingress",
        rule_provider: "azure",
        rule_service: "network",
        impact:
          "Publicly accessible ports could expose the network to unauthorized access",
        resolution: "Restrict access to specific IP addresses or ranges",
        links: [
          "https://docs.microsoft.com/en-us/azure/security/fundamentals/network-best-practices",
          "https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/network_security_rule",
        ],
        description:
          "NSG allows inbound traffic from any IP address on port 22 (SSH).",
        severity: "high",
        resource: "nsg:dev-servers",
        createdAt: new Date("2023-10-07T12:00:00Z"),
        updatedAt: new Date("2023-10-08T12:00:00Z"),
        location: {
          filename: "/terraform/network.tf",
          start_line: 30,
          end_line: 42,
        },
        status: null,
        configurationId: "azure-dev",
        warning: null,
      },
      {
        id: "azure-issue-2",
        rule_id: "AVD-AZR-0045",
        long_id: "azure-storage-default-action-deny",
        rule_description:
          "Storage accounts should have the default network access rule set to deny",
        rule_provider: "azure",
        rule_service: "storage",
        impact: "Unrestricted network access to storage account",
        resolution:
          "Set default action to deny and explicitly allow required networks",
        links: [
          "https://docs.microsoft.com/en-us/azure/storage/common/storage-network-security",
          "https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/storage_account_network_rules",
        ],
        description: "Storage account 'devfiles' allows public blob access.",
        severity: "critical",
        resource: "storage:devfiles",
        createdAt: new Date("2023-10-07T12:00:00Z"),
        updatedAt: new Date("2023-10-08T12:00:00Z"),
        location: {
          filename: "/terraform/storage.tf",
          start_line: 15,
          end_line: 20,
        },
        status: null,
        configurationId: "azure-dev",
        warning: null,
      },
    ],
  },
  "gcp-staging": {
    id: "gcp-staging",
    name: "GCP Production",
    provider: "gcp",
    criticalCount: 2,
    highCount: 5,
    lowCount: 9,
    resources: 98,
    SecurePercentage: 85,
    isPending: false,
    createdAt: new Date("2025-03-01T10:00:00Z"),
    updatedAt: new Date("2025-03-13T14:30:00Z"),
    issues: [
      {
        id: "gcp-issue-1",
        rule_id: "GCP-001",
        long_id: "gcp-storage-public-access",
        rule_description: "Cloud Storage bucket has public access",
        rule_provider: "gcp",
        rule_service: "storage",
        impact: "Unauthorized access to sensitive data",
        resolution:
          "Restrict bucket access to specific users or service accounts",
        links: [
          "https://cloud.google.com/storage/docs/access-control/making-data-public",
          "https://cloud.google.com/storage/docs/access-control/iam",
        ],
        description:
          "The Cloud Storage bucket 'prod-data' is configured with public read access.",
        severity: "critical",
        resource: "gs://prod-data",
        createdAt: new Date("2025-03-10T09:15:00Z"),
        updatedAt: new Date("2025-03-11T11:30:00Z"),
        location: {
          filename: "/terraform/storage.tf",
          start_line: 15,
          end_line: 20,
        },
        status: null,
        configurationId: "gcp-prod",
        warning: null,
      },
      {
        id: "gcp-issue-2",
        rule_id: "GCP-002",
        long_id: "gcp-compute-default-service-account",
        rule_description: "Compute instance using default service account",
        rule_provider: "gcp",
        rule_service: "compute",
        impact: "Overly permissive access for compute instances",
        resolution:
          "Use custom service accounts with minimal required permissions",
        links: [
          "https://cloud.google.com/compute/docs/access/service-accounts",
          "https://cloud.google.com/iam/docs/best-practices-for-using-and-managing-service-accounts",
        ],
        description:
          "Compute instance 'prod-server-1' is using the default compute service account.",
        severity: "high",
        resource: "compute/prod-server-1",
        createdAt: new Date("2025-03-12T14:20:00Z"),
        updatedAt: new Date("2025-03-13T10:45:00Z"),
        location: {
          filename: "/terraform/compute.tf",
          start_line: 30,
          end_line: 45,
        },
        status: null,
        configurationId: "gcp-prod",
        warning: null,
      },
    ],
  },
};
